version: '3.8'

services:
  mestre:
    build: ./mestre
    container_name: mestre
    ports:
      # Expõe a porta 8080 do container para a porta 8080 da sua máquina
      - "8080:8080"
    depends_on:
      - escravo1
      - escravo2

  escravo1:
    build: escravo1
    container_name: escravo1

  escravo2:
    build: escravo2
    container_name: escravo2